package dzve.model;

public enum Permission {
    CAN_MANAGE_BANK,
    CAN_UPDATE_GROUP,
    CAN_INVITE,
    CAN_CHANGE_ROLE,
    CAN_KICK,
    CAN_MANAGE_ROLE,
    CAN_MANAGE_HOME,
    CAN_MANAGE_CLAIM,
    CAN_MANAGE_DIPLOMACY,
    CAN_INTERACT_IN_CLAIM,
    CAN_TELEPORT_HOME,
    CAN_CHAT_INTERNAL,
    CAN_CHAT_ALLY,
    CAN_UPGRADE_GUILD,
}
